---
title: "Week 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


---
title: "Data Analysis in Social Science  (25 January)"
output:
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Exercise 1.

Open the xwavedat.tab data set in the ukhls_wx folder. What data does it contain? 

```{r}
library(tidyverse)

w10 <- read_tsv("UKDA-6614-tab/tab/ukhls_wx/xwavedat.tab")
```

## Exercise 2.

Open the j_egoalt data set in the ukhls_w10 folder. What data does it contain? 
```{r}
w10ego <- read_tsv("UKDA-6614-tab/tab/ukhls_w10/j_egoalt.tab")

## shows relationships between couples. Whether they are married, brother and sister, father and son etc. 

w10ego %>% 
  filter(j_hidp == 277059218)
```

## Exercise 3.

Open the text of Hamlet in R: https://www.gutenberg.org/files/27761/27761-h/27761-h.htm


```{r}
hamlet <- read_lines("https://www.gutenberg.org/files/27761/27761-h/27761-h.htm", skip = 552)
```

The first row should contain "Ber. Who's there?"
The last row should contain "THE END".